### ISSUE TITLE
onResult called multiple times instead of once

### ISSUE THREAD

**Issue by wsbak** [PhanVanLinh/AndroidPermissionHandler#1]
Hello,

Thanks for this library

Bug description using the Usage example.

User start action and reject (on the 1st or 2nd pop-up) :
onResult is called with All requested permissions is denied

User start action and reject (on the 1st or 2nd pop-up) :
onResult is called **TWICE** 👎  with All requested permissions is denied

User start action and accept  :
onResult is called **3 TIMES** 👎 with All requested permissions is granted

There are some traces :
... has leaked IntentReceiver ...PermissionHandler... that was originally registered here. Are you missing a call to unregisterReceiver()?

Solution which seems to work :
Modify PermissionHandler.java
```
    private void registerBroadcast() {
        BroadcastReceiver mReceiver = new BroadcastReceiver() {
            @Override
            public void onReceive(Context context, Intent intent) {
                updatePermissionResult(findGrantedPermissions(permissions),
                        PackageManager.PERMISSION_GRANTED);
                notifyPermissionResult(this);   <-- added this
            }
        };
        IntentFilter filter = new IntentFilter();
        filter.addAction(Constant.REQUEST_RUNTIME_PERMISSION_ACTION);
        context.registerReceiver(mReceiver, filter);
    }

    private void notifyAllPermissionGranted() {
        updatePermissionResult(permissions, PackageManager.PERMISSION_GRANTED);
        notifyPermissionResult(null);   <-- added null
    }

    private void notifyPermissionResult(BroadcastReceiver receiver) {   <-- added parameter
        if (listener != null) {
            listener.onResult(new RequestPermissionResult(permissions));
        }

        if (receiver != null) {
            context.unregisterReceiver(receiver);   <-- was missing
        }
    }
```

Bye,
Olivier

**Comment by PhanVanLinh** [comment]
Hello Olivier (@wsbak),
Thank you so much for spending your time to use and test my code. I have really appreciated your effort. 
Here is my [Pull Request](https://github.com/PhanVanLinh/AndroidPermissionHandler/pull/2) for fix the leak broadcast receiver
I think it is simple way for fix it in this situation. Do you think it is ok?
I am really sorry because the Usage sample is not correct enough. I will try to make the Usage sample better
If you have any idea or problem please tell me. This is my first library so I am really sorry because it is not good enough and I have bugs. However, I am sure that I will try to improve if I found any problems
Thank you so much.
Your sincerely,
Linh,
Phan Van Linh

**Comment by wsbak** [comment]
Ok for me, pull request obviously better/simpler than my solution.

Regards,
Olivier
